-- 1. 2003년에 입사한 사원들의 사번, 이름, 입사일을 출력
Select EMPLOYEE_ID,FIRST_NAME ||' '|| lAST_NAME AS NAME, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY') LIKE '2003';

-- 2. 업무가 FI_ACCOUNT / FI_MGR / SA_MAN / SA_REP 인 사원들의 정보를 출력
SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE 'FI_ACCOUNT' OR JOB_ID LIKE 'FI_MGR' OR JOB_ID LIKE 'SA_MAN' OR JOB_ID LIKE 'SA_REP';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID IN ('FI_ACCOUNT','FI_MGR','SA_MAN','SA_REP');

-- 3. 커미션을 받는 사원들의 명단을 출력
SELECT FIRST_NAME ||' '|| lAST_NAME AS NAME , commission_pct
FROM EMPLOYEES
WHERE commission_pct >0;

--? 4.업무가 SA_MAN 또는 SA_REP이면 "판매부서"를 그 외는 "그 외 부서"라고 출력
SELECT JOB_ID,DECODE(JOB_ID,'SA_MAN','판매부서','SA_REP','판매부서','그 외 부서') AS 부서명
FROM EMPLOYEES;

SELECT JOB_ID, CASE(JOB_ID)
WHEN 'SA_MAN' THEN '판매부서'
WHEN 'SA_REP' THEN '판매부서'
ELSE '그 외 부서'
END AS 부서명
FROM EMPLOYEES;

-- 5. 연도별로 입사자들의 최소급여, 최대 급여, 급여의 총합 그리고 평균 급여를 구하시오
SELECT TO_CHAR(HIRE_DATE,'yyyy'),MIN(SALARY) AS 최소급여, MAX(SALARY) AS 최대급여, SUM(SALARY) AS 급여총합, TRUNC(AVG(SALARY)) AS 평균급여
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'yyyy');


-- 6. 부서별 평균 급여가 $10,000 이상인 부서만 구하시오. ( 평균급여가 높은 순으로 )
SELECT TRUNC(AVG(SALARY)) AS 평균급여
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)> 10000
ORDER BY AVG(SALARY) DESC;

-- 7. 부서별 최대 급여를 구하시오.
SELECT DEPARTMENT_ID,MAX(SALARY) AS 최대급여
FROM EMPLOYEES
GROUP BY department_id
ORDER BY MAX(SALARY) DESC;
