-- 1.
ORACLE : 1521
MS - SQL : 1433
MY - SQL : 3306

-- 2 .
alter user SCOTT identified by TIGER;

--3.
Create user SCOTT identified by 1234;
Grant connect,resource, dba to SCOTT;

-- 4.
CREATE TABLE EMP (
 ENO          NUMBER(4),
 ENAME       VARCHAR2(10),
 JOB         VARCHAR2(9),
 MANAGER       NUMBER(4),
 HIREDATE      DATE,
 SALARY      NUMBER(7,2),
 COMMISSION   NUMBER(7,2),
 DNO         NUMBER(2),
 
CONSTRAINTS PK_EMP_ENO PRIMARY KEY (ENO),
CONSTRAINTS FK_EMP_DNO FOREIGN KEY (DNO) REFERENCES DEPT(DNO)
);

CREATE TABLE DEPT (
 DNO      NUMBER(2),
 DNAME   VARCHAR2(14),
 LOC      VARCHAR2(13),

CONSTARINTS PK_DEPT_DNO PRIMARY KEY (DNO)
);


-- 5.
CREATE TABLE SALG (
 GRADE      NUMBER
 LOSAL      NUMBER
 HISAL      NUMBER
);

-- 6.
INSERT INTO DEPT(DNO,DNAME,LOC) VALUES (10,'ACCOUNTING','NEW YORK');

-- 7.
INSERT INTO EMP(ENO,ENAME,JOB,MANAGER,HIREDATE,SALARY,COMMISSION,DNO)
      VALUES(7369,'SMITH','CLERK',7902,TO_DATE('1980/12/17','YY/MM/DD'),800,''(NULL),20);

--8.
INSERT INTO SALG (GRADE,LOSAL,HISAL) VALUES(1,700,1200);

--9.
-- DELETE
DELETE FROM DEPT;
DELETE FROM EMP;
DELETE FROM SALG;

-- TRUNCATE
TRUNCATE DEPT;
TRUNCATE EMP;
TRUNCATE SALG;

-- 10.
DROP TABLE DEPT;
DROP TABLE EMP;
DROP TABLE SALG;