--1
SELECT ENAME,ENO,HIREDATE,SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000 AND 3000
ORDER BY ENAME ASC;

-- 2
SELECT ENAME, ENO
FROM EMPLOYEE
WHERE COMMISSION IS NULL
ORDER BY DNO ASC, ENAME ASC;

-- 3
SELECT ENAME, SALARY, COMMISSION
FROM EMPLOYEE
WHERE COMMISSION IN (300,500,1400)
ORDER BY COMMISSION DESC;

-- 4
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'S%';

--5
SELECT ENAME,HIREDATE
FROM EMPLOYEE
WHERE NOT TO_CHAR(HIREDATE , 'YYYY') LIKE '1981';

--6
SELECT DISTINCT DNO
FROM EMPLOYEE
ORDER BY DNO ASC;

--7
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE ('%A%E%');

--8
SELECT ENO, ENAME,HIREDATE
FROM EMPLOYEE
WHERE SUBSTR(TO_CHAR(HIREDATE,'YYYYMMDD'),5,2) LIKE '12';

--9
SELECT ENAME , SALARY , NVL(COMMISSION,0) , SALARY*12+NVL(COMMISSION,0) AS 연봉
FROM EMPLOYEE
ORDER BY 연봉 DESC; 

-- 10
SELECT ENAME , SALARY , NVL2(COMMISSION,COMMISSION,0) , SALARY*12+NVL2(COMMISSION,COMMISSION,0) AS 연봉
FROM EMPLOYEE
ORDER BY 연봉 DESC; 

-- 11
SELECT SUM(SALARY) AS 급여총액 , AVG(SALARY) AS 평균액 , MAX(SALARY) AS 최고액, MIN(SALARY) AS 최소액
FROM EMPLOYEE;

-- 12
SELECT COUNT(JOB) AS "직업 종류의 갯수"
FROM EMPLOYEE;

-- 13
SELECT DNO AS 부서번호, AVG(SALARY) AS 평균월급
FROM EMPLOYEE
GROUP BY DNO;

-- 14
SELECT COUNT(ENAME) AS "동일 업무 사원 수", JOB
FROM EMPLOYEE
GROUP BY JOB;
            
-- 15            
SELECT MIN(SALARY)
FROM EMPLOYEE
WHERE MANAGER IS NOT NULL
GROUP BY JOB
HAVING NOT MIN(SALARY) < 2000
ORDER BY MIN(SALARY) DESC;


-- 16
SELECT ENAME AS 담당이름 , JOB AS 담당업무
FROM EMPLOYEE
WHERE JOB IN (SELECT JOB FROM EMPLOYEE WHERE ENO = 7788);

-- 17
SELECT ENAME AS 사원이름 , JOB AS 담당업무
FROM EMPLOYEE
WHERE SALARY > (SELECT SALARY FROM EMPLOYEE WHERE ENO = 7499);

-- 18
SELECT E2.ENAME,E2.SALARY,E2.DNO
FROM (SELECT MIN(SALARY) AS 최소급여 FROM EMPLOYEE GROUP BY DNO) E1 INNER JOIN EMPLOYEE E2
                                          ON E1.최소급여 = E2.SALARY;

SELECT ENAME,SALARY,DNO
FROM EMPLOYEE
WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEE GROUP BY DNO);
                                       
-- 19
SELECT ENO, ENAME
FROM EMPLOYEE
WHERE SALARY > (SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEE )
ORDER BY SALARY ASC;

-- 20
SELECT E.DNO , E.ENAME, E.JOB
FROM EMPLOYEE E RIGHT OUTER JOIN (SELECT DNO AS DNO FROM DEPT WHERE DNAME LIKE 'RESEARCH') D
         ON E.DNO = D.DNO;

SELECT E.DNO , E.ENAME, E.JOB
FROM (SELECT DNO  AS DNO FROM DEPT WHERE DNAME LIKE 'RESEARCH') D LEFT OUTER JOIN EMPLOYEE E
                                 ON D.DNO = E.DNO;
