--1
SELECT ENAME,ENO,HIREDATE,SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000 AND 3000
ORDER BY ENAME ASC;

-- 2
SELECT ENAME, ENO
FROM EMPLOYEE
WHERE COMMISION IS NULL
ORDER BY DNO ASC, NAME ASC;

-- 3
SELECT ENAME,ROUND(SALARY/12,2) AS 월급,COMMISSION
FROM EMPLOYEE
WHERE COMMISSION IN (300,500,1400)
ORDER BY COMMISSION DESC;


-- 4
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'S%';

--5
SELECT ENAME,HIREDATE
FROM EMPLOYEE
WHERE NOT TO_CHAR(HIREDATE , 'YYYY') LIKE '1981';

--6
SELECT DISTINCT DNO
FROM EMPLOYEE
ORDER BY DNO ASC;

--7
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME IN ('A%','%E');

--8
SELECT ENO, ENAME,HIREDATE
FROM EMPLOYEE
WHERE SUBSTR(TO_CHAR(HIREDATE,'YYYYMMDD'),5,2) LIKE '12';

--9
SELECT ENAME ,ROUND(NVL(SALARY,0)/12,2) ,COMMISION ,NVL(SALARY,0) 
FROM EMPLOYEE
ORDER BY NVL(SALARY,0) DESC; 

-- 10
SELECT ENAME ,ROUND(NVL2(SALARY,SALARY,0)/12,2),COMMISION ,NVL2(SALARY,SALARY,0) 
FROM EMPLOYEE
ORDER BY NVL2(SALARY,SALARY,0) DESC;

-- 11
SELECT SUM(SALARY) AS "급여 총액" , AVG(SALARY) AS "평균액" , MAX(SALARY) AS "최고액", MIN(SALARY) AS "최소액"
FROM EMPLOYEE;

-- 12
SELECT COUNT(JOB) AS "직업 종류의 갯수"
FROM EMPLOYEE;

-- 13
SELECT DNO AS "부서번호", AVG(SALARY) AS "평균월급"
FROM EMPLOYEE
GROUP BY DNO;

-- 14
SELECT COUNT(E1.ENAME)
FROM EMPLOYEE E1 INNER JOIN EMPLOYEE E2
					ON E1.JOB = E2.JOB;
				
-- 15				
SELECT MIN(SAL)
FROM EMPLOYEE
WHERE NOT MANAGER IS NULL AND NOT MIN(SAL) <2000
ORDER BY SALARY DESC;

-- 16
SELECT ENAME,JOB
FROM EMPLOYEE
WHERE JOB IN (SELECT JOB FROM EMPLOYEE WHERE ENO = 7788);

-- 17
SELECT ENAME,JOB
FROM EMPLOYEE
WHERE SALARY > (SELECT SALARY FROM EMPLOYEE WHERE ENO = 7499);

-- 18
SELECT ENAME,JOB,DNO
FROM (SELECT MIN(SALARY) FROM EMPLOYEE GROUP BY DNO) E1 INNER JOIN EMPLOYEE E2
														ON E1.ENAME = E2.ENAME;
													
-- 19
SELECT ENO, ENAME
FROM ()

				